my_blog/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"
urlpatterns = [
    path("signup", views.signup, name="signup"),
]

my_blog/articles/urls.py
from django.urls import path
from articles import views

app_name = "articles"
urlpatterns = [
    path("", views.articles_list, name="articles_list"),
    path("<slug>", views.articles_detail, name="articles_detail"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
]

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # image
from django.conf import settings  # image
from django.conf.urls.static import static  # image

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # image

my_blog/accounts/models.py
from django.db import models

# Create your models here.

my_blog/articles/models.py
from django.db import models

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="default.jpg", blank=True)

    def __str__(self):
        return f"{self.title}"

    def snippet(self):
        return f"{self.body[:100]} ..."

my_blog/accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # login
            # return HttpResponse("shod")
            return redirect("articles:articles_list")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", context={"form": form})

my_blog/articles/views.py
from django.shortcuts import render, HttpResponse
from articles import models

# Create your views here.
def articles_list(request):
    articles = models.Articles.objects.all().order_by("date")
    args = {"articles": articles}
    return render(request, "articles/articles.html", context=args)


def articles_detail(request, slug):
    # return HttpResponse(slug)
    article = models.Articles.objects.get(slug=slug)
    args = {"article": article}
    return render(request, "articles/articles_detail.html", context=args)

my_blog/accounts/templates/accounts/signup.html
{% extends 'articles/base.html' %}
{% block body %}
<h2>signup</h2>
<form action="/accounts/signup" method="post">
    {{ form }} {% csrf_token %}
    <br><input type="submit" value="submit">
</form>
{% endblock %}

my_blog/articles/templates/articles/articles.html
{% extends 'articles/base.html' %}

{% block title %}
articles list
{% endblock %}

{% block body %}
{% for article in articles %}
<h2><a href="{% url 'articles:articles_detail' slug=article.slug %}">{{article.title}}</a></h2>
<p>{{article.snippet}}</p>
<p>{{article.date}}</p>
<hr>
{% endfor %}
{% endblock %}

my_blog/articles/templates/articles/articles_detail.html
{% extends 'articles/base.html' %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block body %}
<h3>{{ article.title }}</h3>
<img src="{{article.image.url}}" alt="">
<p>{{ article.body }}</p>
<p>{{ article.date }}</p>
{% endblock %}

my_blog/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'articles/style.css' %}">
</head>

<body>
    <h1><a href="{% url 'articles:articles_list' %}">articles list</a></h1>
    {% block body %}{% endblock %}
</body>

</html>